packages:
  - apps/*
  - packages/*

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  nodemailer@<8.0.4: '>=8.0.4'
  nodemailer@<=8.0.4: '>=8.0.5'
  serialize-javascript@<7.0.5: '>=7.0.5'
  serialize-javascript@<=7.0.2: '>=7.0.3'
  vite@<=6.4.1: '>=6.4.2'
