import type { ReactNode } from 'react';
export const LUCIDE_ICON_NAMES = [
  'Activity',
  'AlertTriangle',
  'ArrowDown',
  'ArrowDownLeft',
  'ArrowDownRight',
  'ArrowDownUp',
  'ArrowLeft',
  'ArrowLeftRight',
  'ArrowRight',
  'ArrowUp',
  'ArrowUpRight',
  'Bell',
  'Check',
  'CheckCircle2',
  'ChevronDown',
  'ChevronLeft',
  'ChevronRight',
  'Circle',
  'CircleAlert',
  'CircleCheck',
  'CircleDashed',
  'Clock3',
  'CloudOff',
  'Coins',
  'Copy',
  'Download',
  'Ellipsis',
  'ExternalLink',
  'Gauge',
  'Headphones',
  'House',
  'Info',
  'Layers',
  'LoaderCircle',
  'Lock',
  'LockKeyhole',
  'Mail',
  'Minus',
  'Pause',
  'Pencil',
  'Play',
  'Plus',
  'QrCode',
  'RefreshCw',
  'RotateCcw',
  'RotateCw',
  'Scale',
  'Search',
  'Share2',
  'ShieldAlert',
  'ShieldCheck',
  'SkipBack',
  'SkipForward',
  'Sparkles',
  'Trash2',
  'TrendingUp',
  'TriangleAlert',
  'User',
  'Wallet',
  'X',
  'XCircle',
  'Zap',
] as const;
export const lucideStub = Object.fromEntries(
  LUCIDE_ICON_NAMES.map((name) => [name, () => <span data-icon={name} />]),
) as Record<(typeof LUCIDE_ICON_NAMES)[number], () => ReactNode>;
