app = "account-engine"
primary_region = "sin"

[build]
dockerfile = "apps/account-engine/Dockerfile"

[http_service]
auto_start_machines = true
auto_stop_machines = 'stop'
force_https = true
internal_port = 3004
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "256mb"
memory_mb = 256
