# fly.toml app configuration file generated for from-fed-to-chain-api on 2026-05-03T16:33:25+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'from-fed-to-chain-api'
primary_region = 'nrt'
kill_signal = 'SIGINT'
kill_timeout = '30s'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '20s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
