export {
  buildBundlePageUrl,
  buildUserBundleParams,
  computeIsDifferentUser,
  computeRedirectUrl,
  computeShowEmailBanner,
  computeShowQuickSwitch,
  type ConnectedWalletItem,
  EMPTY_CONNECTED_WALLETS,
  findWalletByAddress,
  noopSwitchActiveWallet,
  performWalletSwitchAndRefresh,
  shouldAttemptAutoSwitch,
  shouldRedirectDisconnectedOwner,
} from '@zapengine/app-core/hooks/bundle';
