-- Per-language classroom audio artifacts. Each language_classrooms row gets
-- its own script/hls_url/r2_prefix so a target language can be synthesized
-- and packaged as an independent HLS track, instead of being interleaved into
-- one combined classroom audio. All three columns are nullable and existing
-- rows are left null on purpose: the missing-target predicate in
-- audio-stage.ts is presence-based (a row existing for a target language is
-- enough), so already-published episodes are never regenerated by this
-- migration alone.

begin;

set local lock_timeout = '5s';
set local statement_timeout = '2min';

alter table from_fed_to_chain.language_classrooms
  add column if not exists script text,
  add column if not exists hls_url text,
  add column if not exists r2_prefix text;

-- script and r2_prefix stay service-role-only; only hls_url is safe to expose
-- to Data API clients (mirrors the classroom_hls_url precedent added for
-- episode_localizations in migration 013).
grant select (hls_url)
  on from_fed_to_chain.language_classrooms to anon, authenticated;

notify pgrst, 'reload schema';

commit;
