export const textVariants = {
  headline: 'font-display text-headline',
  verdict: 'font-display-xl text-verdict',
  'display-xl': 'font-display-xl text-display-xl',
  display: 'font-display text-display',
  title: 'font-display text-title',
  heading: 'font-heading text-heading',
  'body-lg': 'font-text text-body-lg',
  body: 'font-text text-body',
  'body-sm': 'font-text text-body-sm',
  caption: 'font-text text-caption',
  action: 'font-text-semibold text-action',
  label: 'font-mono-medium text-label uppercase',
  'data-lg': 'font-data text-data-lg',
  'data-md': 'font-mono-medium text-data-md',
  data: 'font-mono text-data',
} as const;
