import artifact from './distribution-snapshot.json';

/**
 * The committed distribution snapshot behind /distribution.
 *
 * Regenerated by `pnpm social:distribution-snapshot` in the podcast pipeline,
 * which owns the tables. The shape is redeclared here rather than imported
 * because that app is private to the monorepo and ships no types; the
 * `__tests__/distribution.test.ts` suite is what keeps the two in agreement,
 * and it runs in the refresh workflow before anything is committed.
 */

export interface DistributionFunnel {
  articles: number;
  localizations: number;
  videos: number;
  posts: number;
  platforms: number;
  reach: number;
}

export interface DistributionLanguageSummary {
  code: string;
  localizations: number;
  mainAudio: number;
  classroomAudio: number;
  posts: number;
  reach: number;
}

export interface DistributionChannelSummary {
  platform: string;
  language: string;
  posts: number;
  postsWithMetrics: number;
  reach: number;
  likes: number;
  comments: number;
  shares: number;
  firstPostAt: string | null;
  lastPostAt: string | null;
}

export interface DistributionReliability {
  publishJobs: number;
  publishJobsCompleted: number;
  publishJobsFailed: number;
  metricSnapshots: number;
  metricSnapshotsCollected: number;
  strategyVersions: number;
}

export interface DistributionExampleChannel {
  platform: string;
  language: string;
  postUrl: string | null;
  publishedAt: string | null;
}

export interface DistributionExample {
  title: string | null;
  sourceUrl: string;
  createdAt: string;
  localizations: number;
  videos: number;
  posts: number;
  channels: DistributionExampleChannel[];
}

export interface DistributionSnapshot {
  asOf: string;
  coverage: {
    firstEpisodeAt: string | null;
    lastEpisodeAt: string | null;
    firstPostAt: string | null;
    lastPostAt: string | null;
  };
  funnel: DistributionFunnel;
  languages: DistributionLanguageSummary[];
  channels: DistributionChannelSummary[];
  reliability: DistributionReliability;
  example: DistributionExample | null;
}

const PLATFORM_LABELS: Record<string, string> = {
  x: 'X',
  threads: 'Threads',
  rednote: 'Rednote',
  youtube: 'YouTube',
};

const LANGUAGE_LABELS: Record<string, string> = {
  'zh-Hant': 'Chinese',
  ja: 'Japanese',
  en: 'English',
};

export function getDistributionSnapshot(): DistributionSnapshot {
  return artifact as DistributionSnapshot;
}

export function platformLabel(platform: string): string {
  return PLATFORM_LABELS[platform] ?? platform;
}

export function languageLabel(language: string): string {
  return LANGUAGE_LABELS[language] ?? language;
}

export function formatCount(value: number): string {
  return value.toLocaleString('en-US');
}

/** Day precision: the snapshot is refreshed daily, so an hour would be noise. */
export function formatSnapshotDate(iso: string | null): string {
  if (!iso) return 'not yet';
  const parsed = new Date(iso);
  if (Number.isNaN(parsed.getTime())) return 'not yet';
  return parsed.toISOString().slice(0, 10);
}

/**
 * How long the corpus spans, in whole days, so the page can say what the reach
 * figure is a total *over* instead of leaving it undated.
 */
export function coverageDays(snapshot: DistributionSnapshot): number | null {
  const { firstEpisodeAt, lastEpisodeAt } = snapshot.coverage;
  if (!firstEpisodeAt || !lastEpisodeAt) return null;
  const start = new Date(firstEpisodeAt).getTime();
  const end = new Date(lastEpisodeAt).getTime();
  if (Number.isNaN(start) || Number.isNaN(end)) return null;
  return Math.max(1, Math.round((end - start) / 86_400_000));
}

/** Channels a language reaches, so the per-language rows can name them. */
export function channelsForLanguage(
  snapshot: DistributionSnapshot,
  language: string,
): DistributionChannelSummary[] {
  return snapshot.channels.filter((channel) => channel.language === language);
}
