import { expect, it } from 'vitest';
import { replay } from '../facts/replay.js';
import { eventLabel, defendActivity } from './replay.js';
it('reproduces all 63 design labels from source events', () => {
  expect(replay.events.map(eventLabel)).toEqual([
    'Trim BTC · 5% to S&P 500',
    'Trim BTC · 5% to stables',
    'Equal split across assets above their averages',
    'Trim BTC · 5% to S&P 500',
    'Trim BTC + ETH · 10% to stables',
    'Trim S&P 500 · 2.5% to stables',
    'Trim S&P 500 · 2.5% to stables',
    'Trim S&P 500 · 2.5% to stables',
    'Rotate the crypto sleeve to ETH',
    'Trim ETH · 5% to stables',
    'Trim ETH · 5% to stables',
    'Trim ETH · 5% to stables',
    'Trim ETH + S&P 500 · 10% to stables',
    'Trim S&P 500 · 2.5% to stables',
    'Lean from ETH to BTC · 15.12%',
    'Trim BTC + ETH · 10% to S&P 500',
    'Trim BTC + ETH · 10% to stables',
    'Trim ETH · 5% to stables',
    'Trim S&P 500 · 5% to stables',
    'Lean from ETH to BTC · 7.59%',
    'Trim ETH · 5% to stables',
    'Trim ETH · 5% to stables',
    'Trim ETH · 5% to stables',
    'Lean from ETH to BTC · 1.86%',
    'Trim ETH · 5% to stables',
    'Trim S&P 500 · 2.5% to stables',
    'Trim S&P 500 · 2.5% to stables',
    'Trim S&P 500 · 2.5% to stables',
    'Trim S&P 500 · 2.5% to stables',
    'Exit BTC + ETH to stables, in full',
    'Trim S&P 500 · 1.94% to stables',
    'Trim S&P 500 · 1% to stables',
    'Trim S&P 500 · 0.49% to stables',
    'Trim S&P 500 · 0.25% to stables',
    'Trim S&P 500 · 0.12% to stables',
    'Trim S&P 500 · 0.06% to stables',
    'Trim S&P 500 · 0.03% to stables',
    'Trim S&P 500 · 0.02% to stables',
    'Trim S&P 500 · 0.02% to stables',
    'Equal split across assets above their averages',
    'Trim S&P 500 · 2.5% to stables',
    'Trim S&P 500 · 2.5% to stables',
    'Trim S&P 500 · 2.5% to stables',
    'Trim S&P 500 · 2.5% to stables',
    'Trim S&P 500 · 2.5% to stables',
    'Trim S&P 500 · 2.5% to stables',
    'Trim S&P 500 · 2.5% to stables',
    'Trim S&P 500 · 2.5% to stables',
    'Trim S&P 500 · 5% to stables',
    'Trim S&P 500 · 2.5% to stables',
    'Rotate the crypto sleeve to ETH',
    'Trim S&P 500 · 2.5% to stables',
    'Trim S&P 500 · 2.5% to stables',
    'Trim S&P 500 · 2.5% to stables',
    'Trim S&P 500 · 5% to stables',
    'Equal split across assets above their averages',
    'Trim ETH + BTC · 10% to S&P 500',
    'Trim S&P 500 · 5% to stables',
    'Trim BTC · 5% to S&P 500',
    'Trim BTC · 5% to S&P 500',
    'Trim BTC · 5% to S&P 500',
    'Trim BTC + ETH · 10% to S&P 500',
    'Trim BTC + ETH · 10% to S&P 500',
  ]);
  expect(defendActivity()).toEqual({ trims: 17, leans: 3 });
});
