import type { ImageCandidate } from '../../types.js';
import { partitionImageCandidates } from './image-candidates.js';
import { containsEntityPhrase } from './storyboard/english-text.js';

/** One Brave request returns up to this many candidates, and the whole pool is
 * built from those responses, so the cap is per request rather than per scene. */
export const MAX_SEARCH_CANDIDATES_PER_REQUEST = 100;

/** Ranking only reads where an already-selected asset came from. Declaring the
 * shape here keeps the planner's `PlannedVisualImage` out of this module. */
export interface RankedAgainstAsset {
  sourcePageUrl: string;
}

export function viableCandidates(
  candidates: readonly ImageCandidate[],
  allowedOrigins: readonly ImageCandidate['origin'][],
): ImageCandidate[] {
  return partitionViableCandidates(candidates, allowedOrigins).candidates;
}

/**
 * The same filtering, keeping the reason each candidate was dropped. Brave can
 * return 175 results for a scene that then starves, and every one of those
 * removals happens before a download, so `partitionImageCandidates`' own issue
 * codes plus the decorative rules are the only record of where they went.
 */
export function partitionViableCandidates(
  candidates: readonly ImageCandidate[],
  allowedOrigins: readonly ImageCandidate['origin'][],
): { candidates: ImageCandidate[]; drops: Map<string, number> } {
  const drops = new Map<string, number>();
  const countDrop = (reason: string): void => {
    drops.set(reason, (drops.get(reason) ?? 0) + 1);
  };

  const presentable = candidates.filter((candidate) => {
    const reason = decorativeRejection(candidate);
    if (reason) countDrop(reason);
    return reason === null;
  });
  const { accepted, rejected } = partitionImageCandidates(presentable, {
    allowedOrigins,
    deduplicate: true,
    maxCandidates: MAX_SEARCH_CANDIDATES_PER_REQUEST,
  });
  for (const entry of rejected) {
    countDrop(entry.issues[0]?.code ?? 'unknown');
  }
  return { candidates: accepted, drops };
}

const SEARCH_RANKING_NOISE_WORDS = new Set([
  'adult',
  'and',
  'at',
  'documentary',
  'editorial',
  'in',
  'office',
  'photo',
  'photograph',
  'real',
  'the',
  'using',
  'with',
  'working',
  'world',
]);

const NON_EDUCATIONAL_PENALTY_TERMS = [
  'children',
  'classroom',
  'kids',
  'school',
  'student',
] as const;

const HISTORICAL_PENALTY_TERMS = [
  'archive',
  'black-and-white',
  'historical',
  'history',
  'vintage',
] as const;

const COVER_PENALTY_TERMS = [
  'comparison',
  'definition',
  'explained',
  'strategies',
  'versus',
] as const;

const COVER_SOURCE_PENALTY_TERMS = [
  'linkedin.com',
  'medium.com',
  'substack.com',
  'substackcdn.com',
  'youtube.com',
] as const;

const GENERIC_STOCK_PENALTY_TERMS = [
  'business people',
  'business team',
  'collaborating in office',
  'coworkers',
  'futuristic interface',
  'glowing screen',
  'handshake',
  'hologram',
  'looking at laptop',
  'people working in office',
  'smiling team',
  'team meeting',
  'teamwork',
] as const;

const GENERIC_PODCAST_PENALTY_TERMS = [
  'podcast',
  'microphone',
  'studio',
  'headphones',
  'generic finance',
  'generic crypto coin collage',
  'crypto coin collage',
  'coin collage',
] as const;

const SYNTHETIC_IMAGE_TERMS = [
  '3d illustration',
  '3d render',
  'ai generated',
  'ai-generated',
  'concept art',
  'dall-e',
  'dalle',
  'digital art',
  'generated by ai',
  'generative artwork',
  'midjourney',
  'stable diffusion',
  'synthetic image',
] as const;

const EDITORIAL_OR_OFFICIAL_SOURCE_TERMS = [
  '.gov',
  '.int',
  'apnews.com',
  'bbc.com',
  'bloomberg.com',
  'cnbc.com',
  'coindesk.com',
  'cointelegraph.com',
  'ecb.europa.eu',
  'ethereum.org',
  'federalreserve.gov',
  'ft.com',
  'reuters.com',
  'sec.gov',
  'theblock.co',
  'theguardian.com',
  'whitehouse.gov',
  'wsj.com',
] as const;

const STOCK_PREVIEW_TERMS = [
  '123rf',
  'adobestock',
  'alamy',
  'depositphotos',
  'dreamstime',
  'freepik',
  'gettyimages',
  'istockphoto',
  'shutterstock',
  'stock-photo',
  'stock_photo',
  'vecteezy',
] as const;

// These publishers primarily expose article-cover artwork with the headline
// baked into the pixels. The renderer already burns locale subtitles, so a
// search result from one of these sources would recreate the text-card layout
// that the image-only pipeline is intended to remove.
const TEXT_CARD_PUBLISHER_TERMS = [
  'academy.kku.ac.th',
  'alexablockchain.com',
  'bitget.com',
  'blockchain-council.org',
  'blockchainreporter.net',
  'blogger.googleusercontent.com',
  'blogspot.com',
  'ccn.com',
  'chainaware.ai',
  'chainport.io',
  'collibra.com',
  'corytech.com',
  'dipprofit.com',
  'emilyandblair.com',
  'ideausher.com',
  'klever.org',
  'news.cgtn.com',
  'resourcecenter.systemscouncil.ieee.org',
  'solulab.com',
  'slideteam.net',
  'startupfactory.bg',
  'technollogy.com',
  'uniondevelopers.com',
  'var-meta.com',
] as const;

/**
 * Whether a candidate's own metadata names one of the scene's subjects. This is
 * a ranking bonus and must never become a filter again: as a hard gate it threw
 * away 423 of 423 viable images for one episode before a single download,
 * because a news photograph of a person seldom repeats that person's name in its
 * alt text. Relevance is guaranteed by Brave having answered the subject query.
 *
 * A scene that names nothing has no identity to check and answers true for
 * everything, so callers must not award the bonus in that case.
 *
 * Both token boundaries are required, through the shared `containsEntityPhrase`
 * rather than a normalizer of this module's own. A left-only anchor let a short
 * name earn the full bonus off an unrelated longer word -- "Sui" scored against
 * "man in a business suit" -- and demoted aliases are exactly the short names
 * that arrive here.
 */
export function mentionsAnyEntity(
  candidate: ImageCandidate,
  entities: readonly string[],
): boolean {
  if (entities.length === 0) return true;
  const corpus = normalizedSearchCandidateCorpus(candidate);
  return entities.some((entity) => containsEntityPhrase(corpus, entity));
}

function candidateDimensionScore(candidate: ImageCandidate): number {
  if (!candidate.width || !candidate.height) return 0;
  let score = 0;
  if (Math.max(candidate.width, candidate.height) >= 1920) score += 3;
  const aspectRatio = candidate.width / candidate.height;
  if (aspectRatio >= 0.9 && aspectRatio <= 1.6) score += 3;
  else if (aspectRatio > 1.6 && aspectRatio <= 2.0) score += 1;
  if (aspectRatio < 0.75) score -= 4;
  return score;
}

export function searchCandidateScore(
  candidate: ImageCandidate,
  intent: string,
  existingAssets: readonly RankedAgainstAsset[],
): number {
  const corpus = normalizedSearchCandidateCorpus(candidate);
  const queryTokens = normalizedSearchTokens(intent);
  let score = queryTokens.reduce(
    (sum, token) => sum + (corpus.includes(token) ? tokenMatchScore(token) : 0),
    0,
  );

  const extension = imageFileExtension(candidate.imageUrl);
  if (extension === 'jpg' || extension === 'jpeg') score += 4;
  else if (extension === 'webp') score += 2;
  else if (extension === 'png') score -= 3;

  score += candidateDimensionScore(candidate);

  const normalizedIntent = intent.toLowerCase();
  if (
    !/(?:education|school|student|classroom|children|kids)/i.test(
      normalizedIntent,
    ) &&
    includesAny(corpus, NON_EDUCATIONAL_PENALTY_TERMS)
  ) {
    score -= 30;
  }
  if (
    !/(?:history|historical|archive|vintage)/i.test(normalizedIntent) &&
    includesAny(corpus, HISTORICAL_PENALTY_TERMS)
  ) {
    score -= 20;
  }
  if (
    includesAny(corpus, COVER_PENALTY_TERMS) ||
    corpus.includes(' vs ') ||
    corpus.includes(' vs. ')
  ) {
    score -= 12;
  }
  if (includesAny(corpus, COVER_SOURCE_PENALTY_TERMS)) score -= 12;
  if (includesAny(corpus, GENERIC_STOCK_PENALTY_TERMS)) score -= 16;
  if (
    !/(?:podcast|microphone|studio|headphones)/i.test(normalizedIntent) &&
    includesAny(corpus, GENERIC_PODCAST_PENALTY_TERMS)
  ) {
    score -= 30;
  }

  const sourceHostname = candidateHostname(candidate.sourceUrl);
  if (sourceHostname) {
    if (
      candidate.origin === 'brave' &&
      includesAny(sourceHostname, EDITORIAL_OR_OFFICIAL_SOURCE_TERMS)
    ) {
      score += 18;
    }
    const priorUses = existingAssets.filter(
      (asset) => candidateHostname(asset.sourcePageUrl) === sourceHostname,
    ).length;
    score -= priorUses * 4;
  }
  return score;
}

function normalizedSearchCandidateCorpus(candidate: ImageCandidate): string {
  const raw = `${candidate.altText ?? ''} ${candidate.imageUrl} ${candidate.sourceUrl}`;
  let decoded = raw;
  try {
    decoded = decodeURIComponent(raw);
  } catch {
    // Some publisher URLs contain stray percent signs. The raw value still
    // provides deterministic metadata for ranking.
  }
  return decoded.normalize('NFKC').toLowerCase();
}

function normalizedSearchTokens(intent: string): string[] {
  return [
    ...new Set(
      (
        intent
          .normalize('NFKC')
          .toLowerCase()
          .match(/[\p{L}\p{N}]{2,}/gu) ?? []
      ).filter((token) => !SEARCH_RANKING_NOISE_WORDS.has(token)),
    ),
  ];
}

function tokenMatchScore(token: string): number {
  if (/\d/u.test(token)) return 8;
  return token.length >= 7 ? 5 : 3;
}

function imageFileExtension(rawUrl: string): string | null {
  try {
    const filename = new URL(rawUrl).pathname.split('/').at(-1) ?? '';
    return /\.([a-z\d]+)$/i.exec(filename)?.[1]?.toLowerCase() ?? null;
  } catch {
    return null;
  }
}

export function candidateHostname(rawUrl: string): string | null {
  try {
    return new URL(rawUrl).hostname.toLowerCase();
  } catch {
    return null;
  }
}

function includesAny(value: string, terms: readonly string[]): boolean {
  return terms.some((term) => value.includes(term));
}

/**
 * Returns which decorative rule removed the candidate, or null when it stays.
 * Naming the rule is the point: these run before any download, so a scene that
 * starves here leaves no rejection record of its own.
 */
export function decorativeRejection(candidate: ImageCandidate): string | null {
  const value = normalizedSearchCandidateCorpus(candidate);
  if (
    /(?:^|[./_\-\s])(avatar|emoji|emoticon|favicon|icon|logo|profile|sprite|sticker|thumb|thumbnail|wechat|weibo)(?:[./_\-\s]|$)/i.test(
      value,
    )
  ) {
    return 'decorative-asset';
  }
  if (
    candidate.origin === 'brave' &&
    includesAny(value, SYNTHETIC_IMAGE_TERMS)
  ) {
    return 'synthetic-image';
  }
  if (includesAny(value, STOCK_PREVIEW_TERMS)) return 'stock-preview';
  if (includesAny(value, TEXT_CARD_PUBLISHER_TERMS))
    return 'text-card-publisher';
  if (
    candidate.origin === 'brave' &&
    looksLikeTextHeavySearchResult(candidate)
  ) {
    return 'text-heavy-result';
  }
  return null;
}

function looksLikeTextHeavySearchResult(candidate: ImageCandidate): boolean {
  const altText = candidate.altText?.toLowerCase() ?? '';
  const urlMetadata =
    `${candidate.imageUrl} ${candidate.sourceUrl}`.toLowerCase();
  const textHeavyAlt =
    /\b(infographic|diagram|chart|presentation|slides?|poster|tutorial|screenshot|template|wallpaper|quote|whitepaper|explainer)\b/i;
  const instructionalAlt =
    /\bhow\s+to\b/i.test(altText) ||
    /\bwhat\s+is\b/i.test(altText) ||
    /\bwhat\s+are\b/i.test(altText) ||
    /\btypes?\s+of\b/i.test(altText) ||
    /\bstep[- ]by[- ]step\b/i.test(altText) ||
    /\bbeginners?\s+guide\b/i.test(altText) ||
    /\bbeginner's\s+guide\b/i.test(altText) ||
    /\btop\s+\d+\b/i.test(altText);
  const textHeavyUrlTerms = [
    'blog-creative',
    'blog_creative',
    'diagram',
    'infographic',
    'poster',
    'powerpoint',
    'presentation',
    'quote',
    'screenshot',
    'slide',
    'template',
    'thumbnail-with-play',
    'tutorial',
    'types-of',
    'types_of',
    'use-case',
    'use_case',
  ] as const;
  const textHeavySourceTerms = [
    '.pdf',
    '.ppt',
    '.pptx',
    '/quotes/',
    'canva.com',
    'quotefancy.com',
    'scribd.com',
    'slideshare.net',
  ] as const;
  const chineseTextCard =
    /(?:資訊圖|圖表|簡報|投影片|海報|教學|懶人包|排行榜|排名|報告)/u;
  return (
    textHeavyAlt.test(altText) ||
    instructionalAlt ||
    chineseTextCard.test(altText) ||
    includesAny(urlMetadata, textHeavyUrlTerms) ||
    includesAny(urlMetadata, textHeavySourceTerms)
  );
}

export function canonicalCandidateUrl(rawUrl: string): string | null {
  try {
    const url = new URL(rawUrl);
    url.hash = '';
    return url.href;
  } catch {
    return null;
  }
}
