from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

REQUIRED_SERIES = frozenset({"btc", "eth", "spy", "eth_btc", "fgi", "macro_fear_greed"})
DEFAULT_OUTPUT = (
    Path(__file__).resolve().parents[3]
    / "landing-page"
    / "src"
    / "data"
    / "market-signals.json"
)


def validate_dashboard_payload(payload: dict[str, Any]) -> None:
    """Reject incomplete dashboards before they can become a public artifact."""
    series = payload.get("series")
    if not isinstance(series, dict):
        raise ValueError("market dashboard series registry is missing")
    missing = REQUIRED_SERIES.difference(series)
    if missing:
        raise ValueError(
            f"market dashboard is missing series: {', '.join(sorted(missing))}"
        )

    snapshots = payload.get("snapshots")
    if not isinstance(snapshots, list) or not snapshots:
        raise ValueError("market dashboard snapshots must not be empty")

    meta = payload.get("meta")
    if not isinstance(meta, dict) or meta.get("count") != len(snapshots):
        raise ValueError("market dashboard meta.count does not match snapshots")

    last = snapshots[-1]
    if not isinstance(last, dict) or not last.get("snapshot_date"):
        raise ValueError("market dashboard last snapshot_date is missing")


def normalize_meta_timestamp(payload: dict[str, Any]) -> dict[str, Any]:
    """Make the generated bytes depend on market data, not the request clock."""
    last_snapshot_date = payload["snapshots"][-1]["snapshot_date"]
    payload["meta"]["timestamp"] = f"{last_snapshot_date}T00:00:00Z"
    return payload


def write_payload(payload: dict[str, Any], out: Path) -> None:
    if not out.parent.is_dir():
        raise FileNotFoundError(out.parent)
    out.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate the landing-page market signals artifact."
    )
    parser.add_argument("--days", type=int, default=365)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    db_url = os.environ.get("DATABASE_READ_ONLY_URL", "")
    if not db_url or db_url == "placeholder_db_url":
        print(
            "SKIP: DATABASE_READ_ONLY_URL not configured; market signals require "
            "the production read-only database.",
            file=sys.stderr,
        )
        raise SystemExit(0)

    from fastapi.testclient import TestClient

    from src.main import app

    with TestClient(app) as client:
        response = client.get(f"/api/v2/market/dashboard?days={args.days}")
        response.raise_for_status()
        payload = response.json()

    validate_dashboard_payload(payload)
    write_payload(normalize_meta_timestamp(payload), args.out)
    print(f"✓ wrote {args.out} ({len(payload['snapshots'])} daily points)")


if __name__ == "__main__":
    main()
