import { ImageResponse } from 'next/og';
import { MESSAGES } from '@/config/messages';
import { PITCH_OG } from '@/config/pitch';
import { CAPABILITIES, STATUS_LABEL } from '@zapengine/zap-pilot-story/facts';

/**
 * Static OG card for /pitch.
 *
 * Generated by Next.js at build time (compatible with `output: 'export'`) and
 * emitted as `/pitch/opengraph-image.png`. The metadata in `app/pitch/layout.tsx`
 * picks it up automatically — no manual og:image config needed.
 *
 * Constraints: rendered by Satori, which only supports a CSS subset. Every
 * element with multiple children must declare `display: flex`. Avoid
 * `color-mix()`, `background-clip: text`, and `backdrop-filter`.
 */

export const alt = 'Zap Pilot — Investor Pitch';
export const size = { width: 1200, height: 630 };
export const contentType = 'image/png';

// Required for `output: 'export'` — Next.js needs an explicit signal that
// this OG route is rendered at build time, not on demand.
export const dynamic = 'force-static';
export const revalidate = false;

export default function PitchOpenGraphImage() {
  return new ImageResponse(
    <div
      style={{
        width: '100%',
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        padding: '72px 80px',
        // Satori only accepts gradients in `backgroundImage` — bare colors via
        // `background` shorthand are rejected with "Invalid background image".
        backgroundColor: '#0a0a0a',
        backgroundImage:
          'radial-gradient(ellipse 70% 38% at 78% 12%, rgba(212, 197, 163, 0.18), transparent 68%)',
        color: '#f4f4f5',
      }}
    >
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: 18,
        }}
      >
        <img
          width={32}
          height={32}
          alt=""
          src={`data:image/svg+xml,${encodeURIComponent(
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="4 4 56 56" fill="none">' +
              '<g stroke="#d4c5a3" stroke-linecap="round">' +
              '<path d="M16.5 49.5 A24 24 0 1 1 47.5 49.5" stroke-width="4.5"/>' +
              '<line x1="32" y1="32" x2="42.5" y2="13.8" stroke-width="3.4"/></g>' +
              '<circle cx="32" cy="32" r="3.6" fill="#d4c5a3"/></svg>',
          )}`}
        />
        <span
          style={{
            fontSize: 20,
            color: '#a1a1aa',
            letterSpacing: 3,
          }}
        >
          {PITCH_OG.label}
        </span>
      </div>

      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          gap: 24,
          maxWidth: 1040,
        }}
      >
        <div
          style={{
            fontSize: 76,
            lineHeight: 1.04,
            fontWeight: 400,
            color: '#f4f4f5',
          }}
        >
          {MESSAGES.common.brandLine}
        </div>
        <div
          style={{
            fontSize: 28,
            color: '#d4c5a3',
            letterSpacing: 0.3,
          }}
        >
          {MESSAGES.hero.eyebrow}
        </div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 12 }}>
          {MESSAGES.hero.chips.map((chip) => (
            <div
              key={chip.text}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 10,
                fontSize: 20,
                color: '#f4f4f5',
              }}
            >
              <span
                style={{
                  border: '1px solid rgba(255, 255, 255, 0.24)',
                  borderRadius: 999,
                  padding: '2px 10px',
                  fontSize: 14,
                  letterSpacing: 1.5,
                  color: '#a1a1aa',
                }}
              >
                {STATUS_LABEL[
                  CAPABILITIES[chip.capability].status
                ].toUpperCase()}
              </span>
              {chip.text}
            </div>
          ))}
        </div>
      </div>

      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'flex-end',
          fontSize: 18,
          color: '#a1a1aa',
        }}
      >
        <span>{PITCH_OG.url}</span>
        <span style={{ letterSpacing: 2 }}>{PITCH_OG.footer}</span>
      </div>
    </div>,
    { ...size },
  );
}
