import tokens from '@zapengine/design-tokens/tokens.json';
import { ImageResponse } from 'next/og';
import { MESSAGES } from '@/config/messages';
import { PITCH_OG } from '@/config/pitch';
import { CAPABILITIES, STATUS_LABEL } from '@zapengine/zap-pilot-story/facts';

/**
 * Static OG card for /pitch.
 *
 * Generated by Next.js at build time (compatible with `output: 'export'`) and
 * emitted as `/pitch/opengraph-image.png`. The metadata in `app/pitch/layout.tsx`
 * picks it up automatically — no manual og:image config needed.
 *
 * Constraints: rendered by Satori, which only supports a CSS subset. Every
 * element with multiple children must declare `display: flex`. Avoid
 * `color-mix()`, `background-clip: text`, and `backdrop-filter`.
 */

export const alt = 'Zap Pilot — Investor Pitch';
export const size = { width: 1200, height: 630 };
export const contentType = 'image/png';

// Required for `output: 'export'` — Next.js needs an explicit signal that
// this OG route is rendered at build time, not on demand.
export const dynamic = 'force-static';
export const revalidate = false;

export default function PitchOpenGraphImage() {
  return new ImageResponse(
    <div
      style={{
        width: '100%',
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        padding: '72px 80px',
        // Satori only accepts gradients in `backgroundImage` — bare colors via
        // `background` shorthand are rejected with "Invalid background image".
        backgroundColor: tokens.mode.paper.ground,
        color: tokens.mode.paper.ink,
      }}
    >
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: 18,
        }}
      >
        <img
          width={32}
          height={32}
          alt=""
          src={`data:image/svg+xml,${encodeURIComponent(
            `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" fill="none"><path d="${tokens.mark.layers[0]!.d}" stroke="${tokens.mode.paper.ink}" stroke-width="2.2"/><path d="${tokens.mark.layers[1]!.d}" stroke="${tokens.mode.paper.ink}" stroke-width="1.6"/><path d="${tokens.mark.layers[2]!.d}" stroke="${tokens.mode.paper['sign-ink']}" stroke-width="2.2"/><circle cx="16" cy="16" r="2.6" fill="${tokens.mode.paper.ink}"/></svg>`,
          )}`}
        />
        <span
          style={{
            fontSize: 20,
            color: tokens.mode.paper['ink-2'],
            letterSpacing: 3,
          }}
        >
          {PITCH_OG.label}
        </span>
      </div>

      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          gap: 24,
          maxWidth: 1040,
        }}
      >
        <div
          style={{
            fontSize: 76,
            lineHeight: 1.04,
            fontWeight: 400,
            color: tokens.mode.paper.ink,
          }}
        >
          {MESSAGES.common.brandLine}
        </div>
        <div
          style={{
            fontSize: 28,
            color: tokens.mode.paper['sign-ink'],
            letterSpacing: 0.3,
          }}
        >
          {MESSAGES.hero.eyebrow}
        </div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 12 }}>
          {MESSAGES.hero.chips.map((chip) => (
            <div
              key={chip.text}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 10,
                fontSize: 20,
                color: tokens.mode.paper.ink,
              }}
            >
              <span
                style={{
                  border: `1px solid ${tokens.mode.paper.rule}`,
                  borderRadius: 999,
                  padding: '2px 10px',
                  fontSize: 14,
                  letterSpacing: 1.5,
                  color: tokens.mode.paper['ink-2'],
                }}
              >
                {STATUS_LABEL[
                  CAPABILITIES[chip.capability].status
                ].toUpperCase()}
              </span>
              {chip.text}
            </div>
          ))}
        </div>
      </div>

      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'flex-end',
          fontSize: 18,
          color: tokens.mode.paper['ink-2'],
        }}
      >
        <span>{PITCH_OG.url}</span>
        <span style={{ letterSpacing: 2 }}>{PITCH_OG.footer}</span>
      </div>
    </div>,
    { ...size },
  );
}
