import {
  CANONICAL_TOKEN_ADDRESSES,
  NATIVE_TOKEN_ADDRESS,
} from '@zapengine/types/shared';
import type { Address } from 'viem';

export const SUPPORTED_CHAINS = {
  ETHEREUM: 1,
  BASE: 8453,
  ARBITRUM: 42161,
} as const;

export const USDC_ADDRESS: Record<number, Address> = {
  [SUPPORTED_CHAINS.ETHEREUM]:
    CANONICAL_TOKEN_ADDRESSES[SUPPORTED_CHAINS.ETHEREUM].USDC,
  [SUPPORTED_CHAINS.BASE]:
    CANONICAL_TOKEN_ADDRESSES[SUPPORTED_CHAINS.BASE].USDC,
  [SUPPORTED_CHAINS.ARBITRUM]:
    CANONICAL_TOKEN_ADDRESSES[SUPPORTED_CHAINS.ARBITRUM].USDC,
};

export const NATIVE_TOKEN: Record<number, Address> = {
  [SUPPORTED_CHAINS.ETHEREUM]: NATIVE_TOKEN_ADDRESS,
  [SUPPORTED_CHAINS.BASE]: NATIVE_TOKEN_ADDRESS,
  [SUPPORTED_CHAINS.ARBITRUM]: NATIVE_TOKEN_ADDRESS,
};
