ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;

ALTER TABLE IF EXISTS portfolio_item_snapshots
    ADD COLUMN IF NOT EXISTS user_id TEXT,
    ADD COLUMN IF NOT EXISTS detail JSONB,
    ADD COLUMN IF NOT EXISTS debt_usd_value NUMERIC,
    ADD COLUMN IF NOT EXISTS pool_symbols TEXT[];
